#!/usr/bin/env python
"""
Fundamental stock analyzer.

This script fetches public market and financial statement data with yfinance,
normalizes common metrics, scores research quality, and optionally blends in a
news signal generated by process_news.py.

It is a research triage tool, not investment advice.
"""

import argparse
import html
import json
import math
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


Metric = Optional[float]


INCOME_ROWS = {
    "revenue": ["Total Revenue", "Operating Revenue"],
    "gross_profit": ["Gross Profit"],
    "operating_income": ["Operating Income", "EBIT"],
    "net_income": ["Net Income", "Net Income Common Stockholders"],
    "diluted_eps": ["Diluted EPS", "Basic EPS"],
}

BALANCE_ROWS = {
    "equity": [
        "Stockholders Equity",
        "Total Equity Gross Minority Interest",
        "Common Stock Equity",
    ],
    "assets": ["Total Assets"],
    "liabilities": [
        "Total Liabilities Net Minority Interest",
        "Total Liab",
        "Total Liabilities",
    ],
    "debt": ["Total Debt", "Long Term Debt", "Net Debt"],
    "cash": [
        "Cash And Cash Equivalents",
        "Cash Cash Equivalents And Short Term Investments",
        "Cash And Short Term Investments",
    ],
    "current_assets": ["Current Assets", "Total Current Assets"],
    "current_liabilities": ["Current Liabilities", "Total Current Liabilities"],
}

CASHFLOW_ROWS = {
    "operating_cash_flow": ["Operating Cash Flow", "Total Cash From Operating Activities"],
    "capex": ["Capital Expenditure", "Capital Expenditures"],
    "free_cash_flow": ["Free Cash Flow"],
    "dividends_paid": ["Cash Dividends Paid", "Dividends Paid"],
    "buybacks": ["Repurchase Of Capital Stock", "Repurchase Of Stock"],
}


def utc_now_text() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def safe_float(value: Any) -> Metric:
    if value is None:
        return None
    try:
        if isinstance(value, str):
            value = value.replace(",", "").replace("%", "").strip()
            if value == "":
                return None
        number = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(number) or math.isinf(number):
        return None
    return number


def safe_div(numerator: Any, denominator: Any) -> Metric:
    num = safe_float(numerator)
    den = safe_float(denominator)
    if num is None or den is None or den == 0:
        return None
    return num / den


def safe_growth(latest: Any, previous: Any) -> Metric:
    latest_f = safe_float(latest)
    previous_f = safe_float(previous)
    if latest_f is None or previous_f is None or previous_f == 0:
        return None
    # If the prior period was negative, percentage growth is often misleading.
    if previous_f < 0:
        return None
    return latest_f / previous_f - 1


def coalesce(*values: Any) -> Metric:
    for value in values:
        f = safe_float(value)
        if f is not None:
            return f
    return None


def pct(value: Metric) -> Optional[str]:
    if value is None:
        return None
    return f"{value * 100:.1f}%"


def compact_number(value: Metric) -> Optional[str]:
    if value is None:
        return None
    abs_value = abs(value)
    if abs_value >= 1_000_000_000_000:
        return f"{value / 1_000_000_000_000:.2f}T"
    if abs_value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    if abs_value >= 1_000_000:
        return f"{value / 1_000_000:.2f}M"
    if abs_value >= 1_000:
        return f"{value / 1_000:.2f}K"
    return f"{value:.2f}"


def read_watchlist(path: Path) -> List[Dict[str, str]]:
    import pandas as pd

    df = pd.read_csv(path)
    if "ticker" not in df.columns:
        raise ValueError("Watchlist CSV must contain a 'ticker' column.")
    rows: List[Dict[str, str]] = []
    for _, row in df.iterrows():
        rows.append({str(k): "" if pd.isna(v) else str(v) for k, v in row.items()})
    return rows


def parse_ticker_list(value: str) -> List[Dict[str, str]]:
    rows = []
    for raw in value.split(","):
        ticker = raw.strip()
        if ticker:
            rows.append({"ticker": ticker, "company": "", "aliases": "", "country": "", "sector": ""})
    return rows


def slice_profiles(rows: List[Dict[str, str]], offset: int, limit: Optional[int]) -> List[Dict[str, str]]:
    if offset < 0:
        raise ValueError("offset must be >= 0")
    if limit is not None and limit < 1:
        raise ValueError("limit must be >= 1")
    sliced = rows[offset:]
    return sliced[:limit] if limit else sliced


def normalize_index_name(value: Any) -> str:
    return str(value).strip().lower().replace("_", " ")


def row_series(df: Any, aliases: Iterable[str]) -> Any:
    if df is None or getattr(df, "empty", True):
        return None
    alias_map = {normalize_index_name(idx): idx for idx in df.index}
    for alias in aliases:
        key = normalize_index_name(alias)
        if key in alias_map:
            return df.loc[alias_map[key]]
    for alias in aliases:
        key = normalize_index_name(alias)
        for normalized, original in alias_map.items():
            if key in normalized:
                return df.loc[original]
    return None


def latest_values(df: Any, aliases: Iterable[str], count: int = 2) -> List[Metric]:
    series = row_series(df, aliases)
    if series is None:
        return []
    values = []
    for value in list(series.values)[:count]:
        values.append(safe_float(value))
    return values


def first_value(df: Any, aliases: Iterable[str]) -> Metric:
    values = latest_values(df, aliases, 1)
    return values[0] if values else None


def average_latest_two(df: Any, aliases: Iterable[str]) -> Metric:
    values = [v for v in latest_values(df, aliases, 2) if v is not None]
    if not values:
        return None
    return sum(values) / len(values)


def value_from_info(info: Dict[str, Any], *keys: str) -> Metric:
    for key in keys:
        if key in info:
            value = safe_float(info.get(key))
            if value is not None:
                return value
    return None


def normalize_yield(value: Metric) -> Metric:
    if value is None:
        return None
    # Some providers return 6.9 for 6.9%, others return 0.069.
    if abs(value) > 1:
        return value / 100
    return value


def fetch_yfinance_package(ticker: str) -> Tuple[Dict[str, Any], Any, Any, Any, List[str]]:
    warnings: List[str] = []
    try:
        import yfinance as yf
    except ImportError as exc:
        raise RuntimeError("yfinance is not installed. Run: pip install -r requirements.txt") from exc

    stock = yf.Ticker(ticker)

    try:
        info = stock.get_info() or {}
    except Exception as exc:  # yfinance providers sometimes throttle or return partial data.
        info = {}
        warnings.append(f"info fetch failed: {exc}")

    def fetch_frame(attr: str) -> Any:
        try:
            frame = getattr(stock, attr)
            if frame is None:
                return None
            if hasattr(frame, "sort_index"):
                return frame
            return None
        except Exception as exc:
            warnings.append(f"{attr} fetch failed: {exc}")
            return None

    financials = fetch_frame("financials")
    balance_sheet = fetch_frame("balance_sheet")
    cashflow = fetch_frame("cashflow")
    return info, financials, balance_sheet, cashflow, warnings


def calculate_metrics(ticker: str, profile: Dict[str, str]) -> Dict[str, Any]:
    info, financials, balance_sheet, cashflow, warnings = fetch_yfinance_package(ticker)

    latest_revenue, prior_revenue = (latest_values(financials, INCOME_ROWS["revenue"], 2) + [None, None])[:2]
    latest_net_income, prior_net_income = (latest_values(financials, INCOME_ROWS["net_income"], 2) + [None, None])[:2]
    gross_profit = first_value(financials, INCOME_ROWS["gross_profit"])
    operating_income = first_value(financials, INCOME_ROWS["operating_income"])

    equity = first_value(balance_sheet, BALANCE_ROWS["equity"])
    avg_equity = average_latest_two(balance_sheet, BALANCE_ROWS["equity"])
    assets = first_value(balance_sheet, BALANCE_ROWS["assets"])
    avg_assets = average_latest_two(balance_sheet, BALANCE_ROWS["assets"])
    liabilities = first_value(balance_sheet, BALANCE_ROWS["liabilities"])
    debt = first_value(balance_sheet, BALANCE_ROWS["debt"])
    cash = first_value(balance_sheet, BALANCE_ROWS["cash"])
    current_assets = first_value(balance_sheet, BALANCE_ROWS["current_assets"])
    current_liabilities = first_value(balance_sheet, BALANCE_ROWS["current_liabilities"])

    operating_cash_flow = first_value(cashflow, CASHFLOW_ROWS["operating_cash_flow"])
    capex = first_value(cashflow, CASHFLOW_ROWS["capex"])
    reported_fcf = first_value(cashflow, CASHFLOW_ROWS["free_cash_flow"])
    free_cash_flow = coalesce(reported_fcf, (operating_cash_flow or 0) + (capex or 0) if operating_cash_flow is not None or capex is not None else None)

    market_cap = value_from_info(info, "marketCap")
    price = coalesce(value_from_info(info, "currentPrice", "regularMarketPrice", "previousClose"))
    trailing_pe = value_from_info(info, "trailingPE")
    forward_pe = value_from_info(info, "forwardPE")
    price_to_book = value_from_info(info, "priceToBook")
    beta = value_from_info(info, "beta")
    dividend_yield = normalize_yield(value_from_info(info, "dividendYield", "trailingAnnualDividendYield"))

    metrics: Dict[str, Any] = {
        "ticker": ticker,
        "company": profile.get("company") or info.get("shortName") or info.get("longName") or "",
        "country": profile.get("country") or info.get("country") or "",
        "sector": profile.get("sector") or info.get("sector") or "",
        "industry": info.get("industry") or "",
        "currency": info.get("currency") or info.get("financialCurrency") or "",
        "price": price,
        "market_cap": market_cap,
        "enterprise_value": value_from_info(info, "enterpriseValue"),
        "beta": beta,
        "trailing_pe": trailing_pe,
        "forward_pe": forward_pe,
        "price_to_book": price_to_book,
        "dividend_yield": dividend_yield,
        "revenue": latest_revenue,
        "revenue_growth": safe_growth(latest_revenue, prior_revenue),
        "gross_margin": safe_div(gross_profit, latest_revenue),
        "operating_margin": safe_div(operating_income, latest_revenue),
        "net_income": latest_net_income,
        "net_income_growth": safe_growth(latest_net_income, prior_net_income),
        "net_margin": safe_div(latest_net_income, latest_revenue),
        "roe": safe_div(latest_net_income, avg_equity or equity),
        "roa": safe_div(latest_net_income, avg_assets or assets),
        "debt_to_equity": safe_div(debt if debt is not None else liabilities, equity),
        "cash_to_debt": safe_div(cash, debt),
        "current_ratio": safe_div(current_assets, current_liabilities),
        "operating_cash_flow": operating_cash_flow,
        "capex": capex,
        "free_cash_flow": free_cash_flow,
        "fcf_margin": safe_div(free_cash_flow, latest_revenue),
        "fcf_yield": safe_div(free_cash_flow, market_cap),
        "earnings_yield": safe_div(latest_net_income, market_cap),
        "financial_data_warnings": "; ".join(warnings),
        "retrieved_at": utc_now_text(),
    }
    return metrics


def clamp(value: float, low: float = 0.0, high: float = 100.0) -> float:
    return max(low, min(high, value))


def score_range(value: Metric, low: float, high: float, invert: bool = False) -> Optional[float]:
    if value is None:
        return None
    if high == low:
        return None
    raw = (value - low) / (high - low)
    if invert:
        raw = 1 - raw
    return clamp(raw * 100)


def weighted_average(items: Iterable[Tuple[Optional[float], float]]) -> Tuple[Optional[float], float]:
    total_weight = 0.0
    available_weight = 0.0
    weighted = 0.0
    for score, weight in items:
        total_weight += weight
        if score is None:
            continue
        available_weight += weight
        weighted += score * weight
    if available_weight == 0:
        return None, 0.0
    return weighted / available_weight, available_weight / total_weight if total_weight else 0.0


def score_fundamentals(metrics: Dict[str, Any]) -> Dict[str, Any]:
    quality, quality_conf = weighted_average(
        [
            (score_range(metrics.get("roe"), 0.00, 0.20), 0.30),
            (score_range(metrics.get("roa"), 0.00, 0.10), 0.15),
            (score_range(metrics.get("net_margin"), 0.00, 0.20), 0.20),
            (score_range(metrics.get("operating_margin"), 0.00, 0.25), 0.20),
            (score_range(metrics.get("fcf_margin"), 0.00, 0.15), 0.15),
        ]
    )
    growth, growth_conf = weighted_average(
        [
            (score_range(metrics.get("revenue_growth"), -0.10, 0.20), 0.55),
            (score_range(metrics.get("net_income_growth"), -0.15, 0.25), 0.45),
        ]
    )
    balance, balance_conf = weighted_average(
        [
            (score_range(metrics.get("debt_to_equity"), 0.50, 3.00, invert=True), 0.45),
            (score_range(metrics.get("cash_to_debt"), 0.00, 1.00), 0.20),
            (score_range(metrics.get("current_ratio"), 0.80, 2.00), 0.25),
            (score_range(metrics.get("fcf_margin"), -0.05, 0.10), 0.10),
        ]
    )
    valuation, valuation_conf = weighted_average(
        [
            (score_range(metrics.get("trailing_pe"), 8.0, 45.0, invert=True), 0.25),
            (score_range(metrics.get("forward_pe"), 8.0, 35.0, invert=True), 0.20),
            (score_range(metrics.get("price_to_book"), 1.0, 8.0, invert=True), 0.20),
            (score_range(metrics.get("fcf_yield"), 0.00, 0.08), 0.20),
            (score_range(metrics.get("earnings_yield"), 0.00, 0.08), 0.15),
        ]
    )
    shareholder, shareholder_conf = weighted_average(
        [
            (score_range(metrics.get("dividend_yield"), 0.00, 0.06), 0.55),
            (score_range(metrics.get("fcf_yield"), 0.00, 0.08), 0.45),
        ]
    )

    final, final_conf = weighted_average(
        [
            (quality, 0.30),
            (growth, 0.20),
            (balance, 0.20),
            (valuation, 0.20),
            (shareholder, 0.10),
        ]
    )
    result = {
        **metrics,
        "quality_score": round(quality, 1) if quality is not None else None,
        "growth_score": round(growth, 1) if growth is not None else None,
        "balance_sheet_score": round(balance, 1) if balance is not None else None,
        "valuation_score": round(valuation, 1) if valuation is not None else None,
        "shareholder_return_score": round(shareholder, 1) if shareholder is not None else None,
        "fundamental_score": round(final, 1) if final is not None else None,
        "data_confidence": round(final_conf * 100, 1),
        "quality_confidence": round(quality_conf * 100, 1),
        "growth_confidence": round(growth_conf * 100, 1),
        "balance_confidence": round(balance_conf * 100, 1),
        "valuation_confidence": round(valuation_conf * 100, 1),
        "shareholder_confidence": round(shareholder_conf * 100, 1),
    }
    result["research_bucket"] = bucket_label(result.get("fundamental_score"), result.get("data_confidence"))
    return result


def bucket_label(score: Metric, confidence: Metric) -> str:
    if score is None:
        return "Data belum cukup"
    if confidence is not None and confidence < 45:
        return "Data tipis - cek sumber primer"
    if score >= 80:
        return "A - fundamental sangat kuat untuk riset lanjut"
    if score >= 65:
        return "B - kuat / layak masuk shortlist"
    if score >= 50:
        return "C - campuran / watchlist"
    return "D - lemah atau butuh bukti tambahan"


def load_news_summary(path: Optional[Path]) -> Dict[str, Dict[str, Any]]:
    if not path:
        return {}
    import pandas as pd

    df = pd.read_csv(path)
    if "ticker" not in df.columns:
        return {}
    result: Dict[str, Dict[str, Any]] = {}
    for _, row in df.iterrows():
        ticker = str(row.get("ticker", "")).strip()
        if ticker:
            result[ticker] = {str(k): row.get(k) for k in df.columns}
    return result


def blend_news_signal(rows: List[Dict[str, Any]], news_summary: Dict[str, Dict[str, Any]]) -> List[Dict[str, Any]]:
    for row in rows:
        ticker = row.get("ticker")
        news = news_summary.get(str(ticker), {})
        avg_sentiment = safe_float(news.get("avg_sentiment"))
        risk_count = safe_float(news.get("risk_article_count")) or 0
        article_count = safe_float(news.get("article_count")) or 0
        news_score = None
        if avg_sentiment is not None:
            news_score = clamp((avg_sentiment + 1) * 50)
        fundamental_score = safe_float(row.get("fundamental_score"))
        if fundamental_score is not None and news_score is not None:
            penalty = min(8.0, risk_count * 1.5)
            row["research_score_with_news"] = round(clamp(fundamental_score * 0.85 + news_score * 0.15 - penalty), 1)
        else:
            row["research_score_with_news"] = fundamental_score
        row["news_avg_sentiment"] = round(avg_sentiment, 3) if avg_sentiment is not None else None
        row["news_article_count"] = int(article_count) if article_count else 0
        row["news_risk_article_count"] = int(risk_count) if risk_count else 0
        row["news_top_headlines"] = news.get("top_headlines", "")
    return rows


def to_serializable(row: Dict[str, Any]) -> Dict[str, Any]:
    cleaned = {}
    for key, value in row.items():
        if hasattr(value, "item"):
            value = value.item()
        if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
            value = None
        cleaned[key] = value
    return cleaned


def write_outputs(rows: List[Dict[str, Any]], output_dir: Path, prefix: str) -> Dict[str, Path]:
    import pandas as pd

    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base = output_dir / f"{prefix}_{timestamp}"
    df = pd.DataFrame([to_serializable(row) for row in rows])

    preferred_columns = [
        "ticker",
        "company",
        "country",
        "sector",
        "currency",
        "price",
        "market_cap",
        "fundamental_score",
        "research_score_with_news",
        "research_bucket",
        "data_confidence",
        "quality_score",
        "growth_score",
        "balance_sheet_score",
        "valuation_score",
        "shareholder_return_score",
        "roe",
        "roa",
        "revenue_growth",
        "net_margin",
        "operating_margin",
        "debt_to_equity",
        "current_ratio",
        "fcf_yield",
        "trailing_pe",
        "forward_pe",
        "price_to_book",
        "dividend_yield",
        "news_avg_sentiment",
        "news_article_count",
        "news_risk_article_count",
        "news_top_headlines",
        "financial_data_warnings",
        "retrieved_at",
    ]
    ordered = [col for col in preferred_columns if col in df.columns] + [col for col in df.columns if col not in preferred_columns]
    df = df[ordered]

    csv_path = base.with_suffix(".csv")
    json_path = base.with_suffix(".json")
    xlsx_path = base.with_suffix(".xlsx")
    html_path = base.with_suffix(".html")

    df.to_csv(csv_path, index=False)
    df.to_json(json_path, orient="records", indent=2, force_ascii=False)
    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Scores")

    html_path.write_text(render_html(df, generated_at=utc_now_text()), encoding="utf-8")
    return {"csv": csv_path, "json": json_path, "xlsx": xlsx_path, "html": html_path}


def render_html(df: Any, generated_at: str) -> str:
    rows_html = []
    display_columns = [
        "ticker",
        "company",
        "fundamental_score",
        "research_score_with_news",
        "research_bucket",
        "data_confidence",
        "roe",
        "revenue_growth",
        "net_margin",
        "debt_to_equity",
        "trailing_pe",
        "fcf_yield",
        "news_avg_sentiment",
    ]
    cols = [col for col in display_columns if col in df.columns]
    for _, row in df.iterrows():
        cells = []
        for col in cols:
            value = row.get(col)
            if col in {"roe", "revenue_growth", "net_margin", "fcf_yield"}:
                value = pct(safe_float(value)) or ""
            elif col in {"market_cap"}:
                value = compact_number(safe_float(value)) or ""
            elif safe_float(value) is not None and col not in {"ticker", "company"}:
                value = f"{safe_float(value):.2f}"
            else:
                value = "" if value is None else str(value)
            cells.append(f"<td>{html.escape(value)}</td>")
        rows_html.append("<tr>" + "".join(cells) + "</tr>")

    header = "".join(f"<th>{html.escape(col.replace('_', ' ').title())}</th>" for col in cols)
    return f"""<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Fundamental Stock Scores</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 32px; color: #17202a; background: #f7f9fb; }}
    main {{ max-width: 1200px; margin: 0 auto; }}
    h1 {{ margin-bottom: 4px; font-size: 28px; }}
    .meta {{ color: #5c6b73; margin-bottom: 24px; }}
    table {{ width: 100%; border-collapse: collapse; background: white; border: 1px solid #dde4ea; }}
    th, td {{ padding: 10px 12px; border-bottom: 1px solid #e7edf2; text-align: left; font-size: 13px; }}
    th {{ background: #edf3f8; color: #20313d; position: sticky; top: 0; }}
    tr:hover {{ background: #f4f8fb; }}
    .note {{ margin-top: 18px; color: #5c6b73; font-size: 13px; line-height: 1.5; }}
  </style>
</head>
<body>
<main>
  <h1>Fundamental Stock Scores</h1>
  <div class="meta">Generated at {html.escape(generated_at)}</div>
  <table>
    <thead><tr>{header}</tr></thead>
    <tbody>{''.join(rows_html)}</tbody>
  </table>
  <p class="note">Skor ini adalah alat triage riset, bukan rekomendasi beli/jual. Selalu cek laporan keuangan resmi, keterkinian data, likuiditas, valuasi relatif, dan risiko berita sebelum mengambil keputusan investasi.</p>
</main>
</body>
</html>
"""


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Analisa fundamental saham Indonesia/global dengan yfinance dan optional sinyal berita.",
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--tickers", help="Daftar ticker dipisah koma. Contoh: BBCA.JK,TLKM.JK,AAPL")
    source.add_argument("--watchlist", type=Path, help="CSV watchlist dengan kolom ticker, company, aliases, country, sector.")
    parser.add_argument("--news-summary", type=Path, help="File news_summary.csv dari process_news.py untuk blend sinyal berita.")
    parser.add_argument("--output-dir", type=Path, default=Path("outputs"), help="Folder output.")
    parser.add_argument("--prefix", default="fundamental_scores", help="Prefix nama file output.")
    parser.add_argument("--offset", type=int, default=0, help="Lewati N ticker pertama untuk proses batch.")
    parser.add_argument("--limit", type=int, help="Batasi jumlah ticker untuk proses batch.")
    parser.add_argument("--sleep", type=float, default=0.0, help="Jeda detik antar ticker untuk mengurangi rate limit.")
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    if args.watchlist:
        watchlist = read_watchlist(args.watchlist)
    else:
        watchlist = parse_ticker_list(args.tickers)

    if not watchlist:
        parser.error("Tidak ada ticker untuk dianalisa.")
    watchlist = slice_profiles(watchlist, args.offset, args.limit)

    rows: List[Dict[str, Any]] = []
    for index, profile in enumerate(watchlist):
        ticker = profile["ticker"].strip()
        print(f"[fundamental] fetching {ticker}...", file=sys.stderr)
        try:
            metrics = calculate_metrics(ticker, profile)
            rows.append(score_fundamentals(metrics))
        except Exception as exc:
            rows.append(
                {
                    "ticker": ticker,
                    "company": profile.get("company", ""),
                    "fundamental_score": None,
                    "research_bucket": "Error saat fetch/normalisasi",
                    "data_confidence": 0,
                    "financial_data_warnings": str(exc),
                    "retrieved_at": utc_now_text(),
                }
            )
        if args.sleep > 0 and index < len(watchlist) - 1:
            time.sleep(args.sleep)

    news_summary = load_news_summary(args.news_summary)
    rows = blend_news_signal(rows, news_summary)
    paths = write_outputs(rows, args.output_dir, args.prefix)

    print("Outputs created:")
    for kind, path in paths.items():
        print(f"- {kind}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
